@startuml
actor Contribuyente
database "Repositorio (en memoria)\nde Hechos y Solicitudes" as DB

node "Servidor MetaMapa" {
  component "Servicio de Fuentes Dinámicas" as FD
  component "Servicio de Fuentes Proxy" as FP {
    component "Fuente Demo" as Demo
    component "Fuente MetaMapa\n(API REST en tiempo real)" as Meta
  }
}

database "Fuente Externa" as Externa
database "API REST\nOtra instancia MetaMapa" as API_REST
Contribuyente --> FD : sube hechos
FD --> DB


Demo --> Externa : consulta una vez por hora
Meta --> API_REST : consumir API en tiempo real
@enduml