@startuml
actor visualizador
actor contribuyente
actor administrador

cloud "Internet" as internet

node "Nodo Cliente\n(GUI)" as nodoCliente
node "Nodo Backend\n" as nodoBackend
database "Fuente Estatica\n(Dataset CSV)" as fuenteCSV

visualizador --> nodoCliente
contribuyente --> nodoCliente
administrador --> nodoCliente

nodoCliente --> internet : HTTP / HTTPS
internet --> nodoBackend
nodoBackend --> fuenteCSV : Lectura
@enduml